// app/lib/mock-raport.ts
import { RaportRecord } from '@/app/types/raport';

export const MOCK_RAPORT_DATA: RaportRecord[] = [
  // Matematika - Evaluasi Perkalian & Pembagian (Juli 2026)
  {
    id: 1,
    id_siswa: 1,
    id_item: 101,
    nilai: 'sangat menguasai',
    keterangan: 'Sudah hafal tabel perkalian 1 sampai 10 dengan sangat lancar dan cepat.',
    tanggal: '2026-07-15',
    label_materi: 'Perkalian Dasar (Tabel 1-10)',
    nama_set: 'Evaluasi Perkalian & Pembagian',
    mapel: 'Matematika',
  },
  {
    id: 2,
    id_siswa: 1,
    id_item: 102,
    nilai: 'sangat menguasai',
    keterangan: 'Mampu menyelesaikan soal cerita perkalian dua digit dengan teliti.',
    tanggal: '2026-07-15',
    label_materi: 'Operasi Perkalian Dua Digit',
    nama_set: 'Evaluasi Perkalian & Pembagian',
    mapel: 'Matematika',
  },
  {
    id: 3,
    id_siswa: 1,
    id_item: 103,
    nilai: 'mulai menguasai',
    keterangan: 'Memahami konsep pembagian bersusun, namun kadang masih perlu bimbingan pada langkah pengurangan.',
    tanggal: '2026-07-16',
    label_materi: 'Pembagian Bersusun (Porogapit)',
    nama_set: 'Evaluasi Perkalian & Pembagian',
    mapel: 'Matematika',
  },
  {
    id: 4,
    id_siswa: 1,
    id_item: 104,
    nilai: 'belum menguasai',
    keterangan: 'Perlu latihan lebih banyak untuk soal cerita kombinasi perkalian dan pembagian.',
    tanggal: '2026-07-16',
    label_materi: 'Soal Cerita Kombinasi Operasi Hitung',
    nama_set: 'Evaluasi Perkalian & Pembagian',
    mapel: 'Matematika',
  },

  // Bahasa Inggris - Vocabulary & Basic Grammar
  {
    id: 5,
    id_siswa: 1,
    id_item: 201,
    nilai: 'sangat menguasai',
    keterangan: 'Sangat baik dalam mengeja dan menyebutkan kosakata benda-benda di sekitar rumah dan sekolah.',
    tanggal: '2026-07-10',
    label_materi: 'Daily Vocabulary & Objects',
    nama_set: 'Daily Conversation & Vocabulary',
    mapel: 'Bahasa Inggris',
  },
  {
    id: 6,
    id_siswa: 1,
    id_item: 202,
    nilai: 'sangat menguasai',
    keterangan: 'Percaya diri saat memperkenalkan diri menggunakan bahasa Inggris sederhana.',
    tanggal: '2026-07-10',
    label_materi: 'Self Introduction & Greetings',
    nama_set: 'Daily Conversation & Vocabulary',
    mapel: 'Bahasa Inggris',
  },
  {
    id: 7,
    id_siswa: 1,
    id_item: 203,
    nilai: 'mulai menguasai',
    keterangan: 'Penggunaan Simple Present Tense sudah baik, namun masih ada kekeliruan kecil pada kata ganti he/she/it.',
    tanggal: '2026-07-12',
    label_materi: 'Basic Sentence Structure (Simple Present)',
    nama_set: 'Daily Conversation & Vocabulary',
    mapel: 'Bahasa Inggris',
  },

  // Mengaji / Tahfidz - Juz Amma & Tajwid
  {
    id: 8,
    id_siswa: 1,
    id_item: 301,
    nilai: 'sangat menguasai',
    keterangan: 'Hafalan lancar dan tartil, tajwid makhraj huruf sangat jelas.',
    tanggal: '2026-07-18',
    label_materi: 'Hafalan Surah An-Naba & An-Nazi\'at',
    nama_set: 'Setoran Hafalan Juz 30',
    mapel: 'Mengaji & Tahfidz',
  },
  {
    id: 9,
    id_siswa: 1,
    id_item: 302,
    nilai: 'sangat menguasai',
    keterangan: 'Hafalan sangat mutqin tanpa banyak jeda.',
    tanggal: '2026-07-18',
    label_materi: 'Hafalan Surah Abasa s/d Al-Infitar',
    nama_set: 'Setoran Hafalan Juz 30',
    mapel: 'Mengaji & Tahfidz',
  },
  {
    id: 10,
    id_siswa: 1,
    id_item: 303,
    nilai: 'mulai menguasai',
    keterangan: 'Hafalan sudah hafal, namun panjang pendek (mad) perlu disempurnakan lagi.',
    tanggal: '2026-07-19',
    label_materi: 'Hukum Tajwid: Nun Mati & Tanwin',
    nama_set: 'Setoran Hafalan Juz 30',
    mapel: 'Mengaji & Tahfidz',
  },

  // IPA / Sains - Eksperimen Sederhana
  {
    id: 11,
    id_siswa: 1,
    id_item: 401,
    nilai: 'sangat menguasai',
    keterangan: 'Sangat aktif dalam mengamati pertumbuhan tanaman dan mencatat hasil pengamatan.',
    tanggal: '2026-07-05',
    label_materi: 'Daur Hidup Tumbuhan & Fotosintesis',
    nama_set: 'Proyek Pembelajaran Sains',
    mapel: 'Sains & IPA',
  },
  {
    id: 12,
    id_siswa: 1,
    id_item: 402,
    nilai: 'mulai menguasai',
    keterangan: 'Dapat membedakan benda padat, cair, dan gas, namun masih perlu pemahaman pada perubahan wujud benda.',
    tanggal: '2026-07-08',
    label_materi: 'Wujud Benda & Perubahannya',
    nama_set: 'Proyek Pembelajaran Sains',
    mapel: 'Sains & IPA',
  }
];
